openapi: 3.0.1
info:
  title: ietf-system
  description: This module contains a collection of YANG definitions for the configuration
    and identification of some common system properties within a device containing
    a NETCONF server.  This includes data node definitions for system identification,
    time-of-day management, user management, DNS resolver configuration, and some
    protocol operations for system management. Copyright (c) 2014 IETF Trust and the
    persons identified as authors of the code.  All rights reserved. Redistribution
    and use in source and binary forms, with or without modification, is permitted
    pursuant to, and subject to the license terms contained in, the Simplified BSD
    License set forth in Section 4.c of the IETF Trust's Legal Provisions Relating
    to IETF Documents (http://trustee.ietf.org/license-info). This version of this
    YANG module is part of RFC 7317; see the RFC itself for full legal notices.
  contact:
    name: API Support
    url: https://github.com/Redocly/redoc
    email: apiteam@swagger.io
  version: 0.0.1
servers:
- url: https://172.20.0.1/restconf/data
tags:
- name: system
  description: System group configuration.
- name: DNS-resolver
  description: Access to Petstore orders
- name: user
  description: Operations about user
paths:
  /ietf-system:system/contact:
    get:
      tags:
      - system
      summary: Contact
      description: The administrator contact information for the system. A server
        implementation MAY map this leaf to the sysContact MIB object.  Such an implementation
        needs to use some mechanism to handle the differences in size and characters
        allowed between this leaf and sysContact.  The definition of such a mechanism
        is outside the scope of this document.
      operationId: getContact
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  Contact:
                    type: string
              example:
                ietf-system:system:
                  contact: This new contact.
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
              example:
                ietf-restconf:errors:
                  error:
                    error-type: application
                    error-tag: invalid-value
                    error-message: Restconf Message is not valid
  /ietf-system:system/hostname:
    get:
      tags:
      - system
      summary: Hostname
      description: The name of the host.  This name can be a single domain label or
        the fully qualified domain name of the host.
      operationId: getHostname
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
              example:
                ietf-system:system:
                  hostname: Switch
  /ietf-system:system/location:
    get:
      tags:
      - system
      summary: Location
      description: The system location. A server implementation MAY map this leaf
        to the sysLocation MIB object.  Such an implementation needs to use some mechanism
        to handle the differences in size and characters allowed between this leaf
        and sysLocation.  The definition of such a mechanism is outside the scope
        of this document.
      operationId: getLocation
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
              example:
                ietf-system:system:
                  location: New Location
  /ietf-system:system/dns-resolver/options/timeout:
    get:
      tags:
      - DNS-resolver
      summary: timeout
      description: The amount of time the resolver will wait for a response from each
        remote name server before retrying the query via a different name server.
      operationId: getDnsTimeout
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
              example:
                ietf-system:system:
                  dns-resolver:
                    options:
                      timeout: "3"
  /ietf-system:system/dns-resolver/options/attempts:
    get:
      tags:
      - DNS-resolver
      summary: attempts
      description: The number of times the resolver will send a query to all of its
        name servers before giving up and returning an error to the calling application.
      operationId: getDnsAttempts
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
              example:
                ietf-system:system:
                  dns-resolver:
                    options:
                      attmepts: "2"
components: {}
